Repository Flux2024/Flux_FrontServer, pull requests merged in 2024-08, with the labels that each got.

#143 feat : login api
  src/assets/image/naver.png
  src/components/login/flux_login.vue
Labels: developing

#145 chore : login page modify
  index.html
  src/components/Oauth2RedirectHandler.vue
  src/components/login/flux_login.vue
  src/router/index.js
  src/stores/auth.js
Labels: developing

#146 feat : login
  src/components/Oauth2RedirectHandler.vue
  src/components/login/flux_login.vue
  src/stores/auth.js
Labels: developing

#147 fix : article
  src/components/article/flux_article_detaile.vue
  src/components/article/flux_article_main.vue
  src/components/manager/flux_manager_article_managerview.vue
  src/components/manager/flux_manager_article_modify.vue
  src/components/manager/flux_manager_article_post.vue
  src/components/manager/flux_manager_article_userlist.vue
Labels: developing

#148 chore : login code modify
  src/components/login/flux_login.vue
Labels: developing

#150 feat : logout
  src/components/Oauth2RedirectHandler.vue
  src/components/header/flux_component_header.vue
  src/components/sidebar/flux_component_side_mypage.vue
  src/stores/auth.js
Labels: developing

#151 chore : login code modify
  src/components/header/flux_component_header.vue
  src/components/sidebar/flux_component_side_mypage.vue
Labels: developing

#154 fix : header update
  src/components/header/flux_component_header.vue
Labels: completed

#155 fix : login, notice
  src/components/header/flux_component_header.vue
  src/components/noti/flux_noti_detail.vue
  src/components/noti/flux_noti_main.vue
  src/router/index.js
  src/stores/rootstore.js
Labels: developing, completed

#157 fix :article post
  src/components/manager/flux_manager_article_post.vue
Labels: completed

#158 fix: article
  src/components/manager/flux_manager_article_managerview.vue
  src/components/manager/flux_manager_article_post.vue
  src/components/manager/flux_manager_article_userlist.vue
Labels: developing

#159 chore : code modify
  src/components/Oauth2RedirectHandler.vue
Labels: developing

#160 fix : manager, mypage side
  src/components/manager/flux_manager_sidebar.vue
  src/components/sidebar/flux_component_side_mypage.vue
Labels: developing, completed

#161 fix:article user
  src/components/article/flux_article_detaile.vue
  src/components/article/flux_article_main.vue
Labels: developing

#162 fix : header style update
  src/components/header/flux_component_header.vue
Labels: developing, completed

#163 chore : login userId
  src/components/Oauth2RedirectHandler.vue
Labels: developing

#164 feat : sales goods add
  src/components/market/flux_market_registration_edit.vue
Labels: completed

#165 fix: article
  src/components/Oauth2RedirectHandler.vue
  src/components/manager/flux_manager_article_post.vue
  src/stores/auth.js
Labels: developing

#167 fix:article vue3
  src/components/article/flux_article_detaile.vue
  src/components/article/flux_article_main.vue
  src/components/manager/flux_manager_article_managerview.vue
  src/components/manager/flux_manager_article_modify.vue
  src/components/manager/flux_manager_article_post.vue
  src/components/manager/flux_manager_article_userlist.vue
Labels: developing

#168 chore : market detail modify
  src/components/market/flux_market_detail.vue
  src/components/market/flux_market_main.vue
  src/components/market/flux_market_registration_edit.vue
  src/router/index.js
Labels: completed

#169 fix:user article page
  src/components/article/flux_article_detaile.vue
  src/components/article/flux_article_main.vue
  src/components/article/flux_article_section.vue
  src/components/sidebar/flux_component_side_article.vue
  src/router/index.js
Labels: developing

#170 chore : detail code modify
  src/components/market/flux_market_section.vue
  src/router/index.js
Labels: completed

#171 feat : comment components update
  src/components/comment/comment.vue
Labels: completed

#172 fix:article, marketDetail
  src/components/article/flux_article_detaile.vue
  src/components/article/flux_article_section.vue
  src/components/manager/flux_manager_article_userlist.vue
  src/components/market/flux_market_detail.vue
  src/components/sidebar/flux_component_side_article.vue
Labels: developing

#173 fix : market side, header noti banner update
  src/components/header/flux_component_header.vue
  src/components/sidebar/flux_component_side_market.vue
Labels: completed

#174 fix : comment api update
  src/components/article/flux_article_detaile.vue
  src/components/article/flux_article_section.vue
  src/components/comment/comment.vue
  src/components/index.vue
  src/components/login/flux_login.vue
  src/router/index.js
Labels: developing, completed

#175 feat : managet usetlist and auth
  src/components/manager/flux_manager_adminlist.vue
  src/components/manager/flux_manager_userlist.vue
Labels: completed

#176 feat : manager header toggle
  src/components/manager/flux_manager_header.vue
Labels: completed

#177 feat : visitor and chart
  package.json
  src/components/manager/flux_manager_main.vue
Labels: developing

#178 chore : visitor modify
  src/components/manager/flux_manager_main.vue
Labels: developing

#180 feat: bid
  src/components/bid/bid.vue
  src/components/manager/flux_manager_article_managerview.vue
  src/components/market/flux_market_detail.vue
  src/router/index.js
Labels: developing

#182 fix : main haeder search delete
  src/components/header/flux_component_header.vue
Labels: completed

#183 chore : visitor modify
  src/App.vue
  src/components/manager/flux_manager_main.vue
  src/stores/visitor.js
Labels: developing, completed

#184 chore : visit modify
  src/App.vue
  src/stores/resetVisitCount.js
Labels: developing

#185 fix : main footer update
  src/components/footer/flux_component_footer.vue
Labels: completed

#186 chore : visitor modify
  src/components/manager/flux_manager_main.vue
Labels: developing

#187 chore : 관지자페이지 메인 스크립트 분리
  src/assets/js/fetchTodayVisitorCount.js
  src/assets/js/fetchVisitorData.js
  src/assets/js/updateChart.js
  src/components/manager/flux_manager_main.vue
Labels: developing

#188 fix:bid
  src/components/bid/bid.vue
  src/components/market/flux_market_detail.vue
  src/components/market/flux_market_main.vue
  src/router/index.js
Labels: developing, completed

#189 fix:market registraion
  src/components/market/flux_market_registration_edit.vue
Labels: completed

#190 프론트 메인 헤더 푸터 수정
  src/components/header/flux_component_header.vue
Labels: completed

#191 feat : 유저수와 신규회원목록 추가
  src/assets/js/fetchUserCount.js
  src/components/manager/flux_manager_main.vue
Labels: developing

#193 fix : notification update
  src/components/header/flux_component_header.vue
  src/components/noti/flux_noti_detail.vue
  src/stores/notice.js
Labels: completed

#194 feat : 권한설정
  src/components/Oauth2RedirectHandler.vue
  src/components/sidebar/flux_component_side_mypage.vue
  src/router/index.js
  src/stores/auth.js
Labels: developing

#195 feat : alert 추가
  src/router/index.js
Labels: developing, completed

#197 Feat1
  src/components/header/flux_component_header.vue
  src/components/index.vue
Labels: developing, completed

#198 Feat1
  src/components/article/flux_article_detaile.vue
  src/components/article/flux_article_main.vue
  src/components/comment/comment.vue
  src/components/index.vue
Labels: developing, completed

#199 feat: 입찰버튼 즉시구매버튼 권한설정
  src/components/bid/bid.vue
Labels: developing

#200 chore : console log 변경
  src/components/Oauth2RedirectHandler.vue
Labels: developing

#201 fix:bid
  src/components/bid/bid.vue
  src/components/market/flux_market_detail.vue
Labels: developing, completed

#202 fix: article modify
  src/components/manager/flux_manager_article_modify.vue
Labels: developing, completed

#203 style : article css update
  src/components/article/flux_article_detaile.vue
  src/components/article/flux_article_main.vue
Labels: completed

#204 fix: mypage_activity
  src/components/mypage/flux_mypage_activity.vue
Labels: developing, completed

#205 fix : maypage_acrivity
  src/components/mypage/flux_mypage_activity.vue
Labels: developing, completed

#206 chore : 이미지 수정
  src/components/market/flux_market_main.vue
Labels: developing

#207 fix: article_detail img
  src/components/article/flux_article_detaile.vue
Labels: developing, completed

#208 fix: article main img
  src/components/article/flux_article_main.vue
Labels: developing, completed

#209 mypage activity img
  src/components/mypage/flux_mypage_activity.vue
Labels: developing, completed

#212 fix : index vue router-link update
  src/components/index.vue
Labels: completed

#213 Feat1
  src/components/Oauth2RedirectHandler.vue
  src/components/article/flux_article_section.vue
  src/components/header/flux_component_header.vue
  src/components/market/flux_market_section.vue
  src/views/article.vue
  src/views/market.vue
Labels: completed

#214 feat : footer modal update
  src/components/footer/flux_component_footer.vue
Labels: completed

#215 Feat1
  src/components/footer/flux_component_footer.vue
  src/components/index.vue
Labels: completed

#216 🔥 fix : rank page access reject
  src/views/ranking.vue
Labels: completed
