Repository Flux2024/Flux_FrontServer, pull requests merged in 2024-07, with the labels that each got.

#2 feat:test close #1
  src/App.vue
Labels: completed

#35 fix : build update
  index.html
  src/assets/css/font.css
  src/assets/css/reset.css
  src/assets/img/favicon.ico
  src/components/header.vue
  src/main.js
Labels: completed

#37 feat : mypage_wishlist
  src/assets/image/img1.png
  src/assets/image/img2.png
  src/components/flux_mypage_wish.vue
Labels: completed

#40 fix : header update v2
  src/components/header.vue
Labels: completed

#41 feat : footer, header update
  src/App.vue
  src/assets/image/github.svg
  src/components/footer.vue
  src/components/header.vue
  src/router/index.js
Labels: completed

#42 feat : mypage_activity
  src/components/error/flux_errorpage.vue
  src/components/mypage/flux_mypage_activity.vue
  src/components/mypage/flux_mypage_wish.vue
Labels: completed

#46 feat : mypage_withdrawal
  src/components/mypage/flux_mypage_withdrawal.vue
Labels: completed

#47 feat : login, footer update
  src/assets/image/googlelogin.png
  src/assets/image/kakaologin.png
  src/assets/image/loginsample.jpg
  src/components/flux_login.vue
  src/components/footer.vue
Labels: completed

#53 fix : test fix
  src/components/flux_login.vue
Labels: completed

#54 feat:articlePost
  src/components/article/articleModify.vue
  src/components/article/articlePost.vue
Labels: completed

#55 feat:articleManagerView
  src/components/article/articleManagerView.vue
Labels: completed

#57 feat : scrollbar, login, sidebar update
  src/assets/css/scrollbar.css
  src/components/login/flux_login.vue
  src/components/sidebar/flux_component_side_market.vue
  src/main.js
Labels: developing

#58 feat:articleModify
  src/components/article/articleModify.vue
Labels: completed

#72 feat : side, header, footer update
  src/App.vue
  src/components/flux_component_footer.vue
  src/components/flux_component_header.vue
  src/components/sidebar/flux_component_side_article.vue
  src/components/sidebar/flux_component_side_market.vue
  src/components/sidebar/flux_component_side_mypage.vue
Labels: completed

#76 rename : manager component rename
  src/components/manager/flux_manager_article_managerview.vue
  src/components/manager/flux_manager_article_modify.vue
  src/components/manager/flux_manager_article_post.vue
  src/components/manager/flux_manager_article_userlist.vue
  src/components/manager/flux_manager_footer.vue
  src/components/manager/flux_manager_header.vue
  src/components/manager/flux_manager_sidebar.vue
Labels: completed

#77 chore : router, store update
  index.html
  src/App.vue
  src/components/article/articleMain.vue
  src/components/article/articleManagerView.vue
  src/components/article/flux_article_detaile.vue
  src/components/article/flux_article_main.vue
  src/components/article/flux_article_section.vue
  src/components/footer/flux_component_footer.vue
  src/components/header/flux_component_header.vue
  src/components/market/Main.vue
  src/components/market/flux_market_detail.vue
  src/components/market/flux_market_main.vue
  src/components/market/flux_market_payment_after.vue
  src/components/market/flux_market_payment_before.vue
  src/components/market/flux_market_registration.vue
  src/components/market/flux_market_registration_edit.vue
  src/components/market/flux_market_registration_info.vue
  src/components/market/flux_market_section.vue
  src/components/mypage/flux_mypage_section.vue
  src/components/rank/flux_rank_main.vue
  src/components/sidebar/flux_component_side_mypage.vue
  src/router/index.js
  src/stores/counter.js
  src/stores/rootstore.js
  src/views/article.vue
  src/views/main.vue
  src/views/market.vue
  src/views/mypage.vue
  src/views/ranking.vue
Labels: developing

#80 feat : manager_main
  src/components/manager/flux_manager_main.vue
Labels: completed

#81 feat:flux_manager_article_userlist
  src/components/manager/flux_manager_article_userlist.vue
Labels: completed

#82 feat:flux_manager_article_notice_edit
  src/components/manager/flux_manager_article_notice_edit.vue
Labels: completed

#83 feat:noticeModify
  src/components/manager/flux_manager_article_notice_modify.vue
Labels: completed

#85 feat:noticemain
  src/components/manager/flux_manager_notice_edit.vue
  src/components/manager/flux_manager_notice_list.vue
  src/components/manager/flux_manager_notice_modify.vue
Labels: completed

#88 feat : managerpage
  package-lock.json
  package.json
  src/App.vue
  src/components/manager/flux_manager_article_managerview.vue
  src/components/manager/flux_manager_article_modify.vue
  src/components/manager/flux_manager_article_post.vue
  src/components/manager/flux_manager_article_section.vue
  src/components/manager/flux_manager_section.vue
  src/components/manager/flux_manager_sidebar.vue
  src/components/manager/flux_manager_userlist.vue
  src/router/index.js
  src/stores/rootstore.js
  src/views/manager_article.vue
  src/views/manager_main.vue
Labels: completed

#89 feat : manager router
  src/components/manager/flux_manager_article_userlist.vue
  src/components/manager/flux_manager_main.vue
Labels: completed

#93 feat : manger_addmindetail
  src/components/manager/flux_manager_admindetail.vue
Labels: completed

#95 feat:notice_router
  src/components/manager/flux_manager_notice_section.vue
  src/router/index.js
  src/stores/rootstore.js
  src/views/manager_notice.vue
Labels: completed

#97 fix : update footer,header,login,mypageside
  src/components/footer/flux_component_footer.vue
  src/components/header/flux_component_header.vue
  src/components/login/flux_login.vue
  src/components/sidebar/flux_component_side_mypage.vue
Labels: developing

#107 fix:notice router, css #106
  src/components/manager/flux_manager_notice_edit.vue
  src/components/manager/flux_manager_notice_list.vue
  src/components/manager/flux_manager_notice_section.vue
  src/components/manager/flux_manager_sidebar.vue
  src/router/index.js
  src/views/manager_notice.vue
Labels: completed

#108 feat : article modifypage router access
  src/components/manager/flux_manager_article_managerview.vue
Labels: completed

#113 feat : header banner update
  package.json
  src/components/header/flux_component_header.vue
  src/main.js
  src/pinia.js
  src/stores/bannerstore.js
Labels: completed

#119 feat2 : json data notices access
  src/components/manager/flux_manager_notice_list.vue
Labels: completed

#127 feat : manager notis api update
  src/components/manager/flux_manager_notice_edit.vue
  src/components/manager/flux_manager_notice_list.vue
  src/components/manager/flux_manager_notice_modify.vue
Labels: completed

#129 fix:article_post #128
  src/components/manager/flux_manager_article_post.vue
Labels: completed

#132 fix:article_main, aticle_sidebar #131
  src/components/article/flux_article_main.vue
  src/components/sidebar/flux_component_side_article.vue
Labels: completed

#133 fix:article manager list #130
  src/components/manager/flux_manager_article_userlist.vue
Labels: completed

#135 feat : manager userlist api
  src/components/manager/flux_manager_notice_modify.vue
  src/components/manager/flux_manager_userlist.vue
Labels: developing, completed

#138 feat : manager_adminlist api
  src/components/manager/flux_manager_adminlist.vue
Labels: completed

#140 fix:manager articlepage
  src/components/manager/flux_manager_article_managerview.vue
  src/components/manager/flux_manager_article_modify.vue
  src/components/manager/flux_manager_article_post.vue
  src/components/manager/flux_manager_article_userlist.vue
Labels: completed
